package es.upm.dit.gsi.trainmining;

import es.upm.dit.gsi.trainmining.model.Alarm;
import es.upm.dit.gsi.trainmining.model.PossibleEvent;

global java.util.List resultList;

rule "test1"
    when
        Alarm(iid : installationID, alarmCode == "eventA");
        Alarm(installationID == iid, alarmCode == "eventB");
    then
    	PossibleEvent p = new PossibleEvent("eventC","alarmtype",iid,0.5);
        resultList.add(p);
        System.out.println("eventC "+iid);
end

rule "test2"
    when
        Alarm(iid : installationID, alarmCode == "eventD");
        Alarm(installationID == iid, alarmCode == "eventE");
    then
    	PossibleEvent p = new PossibleEvent("eventF","alarmtype",iid,0.5);
        resultList.add(p);
        System.out.println("eventF "+iid);
end

rule "rule0"
    when 
        Alarm(iid : installationID, alarmCode == "saml.status.channel_A_CS_down");
        Alarm(installationID == iid, alarmCode == "saml.status.channel_A_CS_unknown");
        Alarm(installationID == iid, alarmCode == "saml.status.energy_switch_rack_general_failure");
    then 
        PossibleEvent p = new PossibleEvent("saml.status.channel_A_CS_unknown","operationsDiagnosisCommunications",iid,0.75707251);
        resultList.add(p);
end

rule "rule1"
    when 
        Alarm(iid : installationID, alarmCode == "saml.status.channel_A_CS_down");
        Alarm(installationID == iid, alarmCode == "saml.status.energy_SAI_line2_nok");
        Alarm(installationID == iid, alarmCode == "saml.status.energy_switch_rack_general_failure");
    then 
        PossibleEvent p = new PossibleEvent("saml.status.channel_A_CS_unknown","operationsDiagnosisCommunications",iid,0.75474119);
        resultList.add(p);
end